---
title: Data and Software

title-block-banner: ../images/envi_met_title.png
title-block-banner-color: black 

---



## Data set for training purposes

Please find all Data Downloads at the [Course Data Server](https://hessenbox.uni-marburg.de/getlink/fi5p6EzMUrtUVFW3DnkFky/envimet) Data folder for any file exchange and data related purposes.


## Specific modeling software 

Please find all Downloads according to ENVI-met at the [ENVI-met landing page](https://envi-met.info/doku.php?id=start)


## Common Software 

Shell — any command line environment will do for the exercises. For Linux we recommend the [bash](http://en.wikipedia.org/wiki/Bash_%28Unix_shell%29) shell. For Windows the Windows command line can be used.

* [QGIS](HTTP://www.qgis.org/de/docs/user_manual/index.html#qgis-manual-index-reference) has become one of the most promising and most integrative open source GIS systems over the last years. Through the processing plugin, it additionally integrates modules from the other leading free GIS solutions. We will need it (if necessary) to prepare or manipulate some of the data.

Regarding installation, for Ubuntu Linux, the [Ubuntu GIS package](https://wiki.ubuntu.com/UbuntuGIS) is a good choice. For Windows, we strongly recommend installing everything via the [OSGeo4W](http://trac.osgeo.org/osgeo4w/) environment and not the standalone QGIS installation tool. 

For most of the data pre and postprocessing, we will use the statistical scripting language [R](https://cran.r-project.org/) and we highly recommend the  [Rstudio](https://rstudio.com/) integrated developing environment. 

Please follow the instructions according to your operating system.


## Additional data sources

You can find information about the "Zukunftsquartier Hasenkopf" in various places:

- City of Marburg [Zukunftsquartier Hasenkopf](https://www.marburg.de/portal/seiten/zukunftsquartier-hasenkopf-900003397-23001.html)
- [Slides](file:///C:/Users/creu/Downloads/2021_09_07_livestream_hasenkopf_wettbewerb_folien_klugm.pdf) including the winning design
- Citizens' initiative wirsindhasenkopf [Flyer](https://wirsindhasenkopf.de/pdf/Flyer_Hasenkopf_Stand_Jan24.pdf) and here “We argue”
- [Envi-met Hasenkopf GIS and Modeldata](https://github.com/gisma-courses/LV-19-d19-010-envi/raw/refs/heads/master/assets/hasenkopf_core_area.zip)
- Digital Elevation Model [DEM]( https://gds.hessen.de/downloadcenter/20241217/3D-Daten/Digitales%20Gel%C3%A4ndemodell%20(DGM1)/Landkreis%20Marburg-Biedenkopf/Marburg%20-%20DGM1.zip) and Digital Surface Model [DSM](https://gds.hessen.de/downloadcenter/20241217/3D-Daten/Digitales%20Oberfl%C3%A4chenmodell%20(DOM1)/Landkreis%20Marburg-Biedenkopf/Marburg%20-%20DOM1.zip) files relevant for Marburg can be downloaded from the [GDS website](https://gds.hessen.de/INTERSHOP/web/WFS/HLBG-Geodaten-Site/de_DE/-/EUR/ViewDownloadcenter-Start) of the Hessian Administration for Land Management and Geoinformation
- For downloading the OSM data it is recommended to use the [OSMDownloader](https://github.com/lcoandrade/OSMDownloader) extension to QGIS. It simply provides the ability to draw a rectangle and download the complete and currently available OSM data to a file named `hasenkopf.osm`. 
- If the data has to be digitised manually, it is advisable to use an up-to-date aerial photograph from Bing or Google. These can be easily integrated via [XYZ tiles](https://search.brave.com/search?q=xyz+bing++and++google+tiles+qgis&source=web&conversation=3edfdf1027de79664f5117&summary=1) 
- The planning data for the development and sealing were taken from page 23 of the [presentation of the winning design](https://www.marburg.de/downloads/datei/YmZlOWFhODY4NDFiNzUxNmxDTUtJYTVFWGRRZDBjUmxSQmFBN2lqRHpKaE9Id0d5cUlrcVdZZTgrdFlZTWdMWHMxK1dzaUJtbVA5a3ZQRmlVZ2hVa01MNkg4cjA3dDJINEFoL1FlazVNdmJVMVl6aXBPMDNYWlhJMzlBU3c5TWpsWUVaUUpKaFp1RC9WcTRkZ29qV2hCVXhFQmxjZkh0cThlU2FqNm5ENnl5SEY1Z2E2eHJPUzBHcWNHUT0) via screenshot.







