name: Quarto Publish

#on:
#  push:
#    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libgl1-mesa-dev \
            libx11-dev \
            libgdal-dev \
            gdal-bin \
            libgeos-dev \
            libproj-dev \
            libudunits2-dev \
            libfreetype6-dev \
            libfontconfig1-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff5-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libreadline-dev \
            pkg-config \
            pandoc

      - name: Cache renv packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore R packages using renv
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore(prompt = FALSE)'

      - name: Render Quarto site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
